version: 0.2

env:
  variables:
    AWS_REGION_NAME: ap-northeast-1
    ECR_REPOSITORY_NAME: laravel_nginx_mysql

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build: # commands to be run before build
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION_NAME})
  build:
    commands:
      - echo Building the Docker image...
      - sudo docker-compose -f docker-compose.prod.yml build
      - echo ${ECR_REPOSITORY_NAME}_app:latest 054974161977.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}_app:latest
      - docker tag ${ECR_REPOSITORY_NAME}_app:latest 054974161977.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}_app:latest
      - echo ${ECR_REPOSITORY_NAME}_web:latest 054974161977.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}_web:latest
      - docker tag ${ECR_REPOSITORY_NAME}_web:latest 054974161977.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}_web:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push ${ECR_REPOSITORY_NAME}_app:latest
      - docker push ${ECR_REPOSITORY_NAME}_web:latest
