version: "3.3"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - ENV=prod
    volumes:
      - ./src/:/app

  web:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - ENV=prod
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src/:/app
    depends_on:
      - app

volumes:
  mysql-volume:
